


# Website Information
title: Kevando
description: Web Surfer


# Website Configuration
url: 'https://kevando.github.io'
google_analytics: UA-16078011-4


# Build Settings
theme: minima
plugins:
    - jekyll-feed

defaults:
    - scope:
          path: ''
      values:
          # Default Values (very important!)
          layout: 'default'
          favicon: icon-32-goat.png
          title: Kevin's Website
          description: Leader of the Internet Retro Revival Wave
          show_navigation: true
          hide_navigation: false
          twitter:
            card: summary
            title: Kevin's Website
            image: https://kevando.github.io/assets/images/aolfav.png
            description: Thanks for stopping by
          og:
            type: website
            title: Kevin's Fresh Website
            image: 
            description: Thanks for chillin w me

# Content

collections:
    category:
        output: true
        defaults:
            - scope:
                  path: ''
                  type: category
              values:
                  layout: 'category'

sass:
    sass_dir: _sass
    style: compressed

# permalink: /:category/:year-:month-:day/:title
include: ['_pages']
