title:
description: Surfing the 90s design revival wave.
url: "https://kevando.github.io"
google_analytics: UA-16078011-4

twitter:
  username: kevando
  card: summary

# Tag Pages (not active)
tag_pages:
  - videos
  - soundcloud

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

collections:
  category:
    output: true
  favs:
    output: true
    permalink: /<3/:name

defaults:
  - scope:
      path: ""
      type: category
    values:
      layout: "category"
