title: Kevin!
description: this my website
url: 'https://kevando.github.io'
google_analytics: UA-16078011-4

# Build Settings
theme: minima
plugins:
    - jekyll-feed
sass:
    sass_dir: _sass\
    style: compressed
include: ['_pages']

# Collections Settings
collections:
    category_pages:
        output: true
        permalink: /:name:output_ext
    lenses:
        output: true
        permalink: /:collection/:name:output_ext

# Fallback Settings 
defaults:
    - scope:
          path: ''
      values:
          # Very important!
          #
          # These are the default variables that get used on every page
          # unless specified otherwise
          layout: default
          title: Kevin's Website
          description: The Internet
          favicon: icon-32-goat.png
          twitter:
              card: summary
              title: Kevin's Website
              image: assets/images/aolfav.png
              description: Thanks for stopping by
          og:
              type: website
              title: Kevin's Fresh Website
              image:
              description: Thanks for chillin w me