# ---------------------------------
#   Basic Shit
# ---------------------------------

title: Kevando
description: Web Surfer
url: "https://kevando.github.io"
google_analytics: UA-16078011-4

# ---------------------------------
#   Build Settings
# ---------------------------------

theme: minima
plugins:
  - jekyll-feed

# ---------------------------------
#   Front Matter Defaults
# ---------------------------------

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      favicon: icon-32-goat.png

# ---------------------------------
#   Content
# ---------------------------------

collections:
  category:
    output: true

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"


sass:
  sass_dir: _sass 
  style: compressed


# permalink: /:category/:year-:month-:day/:title
include: ["_pages"]

