# Website Information
title: Kevin!
description: this my website

# Website Configuration
url: 'https://kevando.github.io'
google_analytics: UA-16078011-4

# Jekyll Build Settings
theme: minima
plugins:
    - jekyll-feed
sass:
    sass_dir: _sass\
    style: compressed
include: ['_pages']

# Collections Config START

collections:
    category_pages:
        output: true
        permalink: /:name:output_ext
    lenses:
        output: true
        permalink: /:collection/:name:output_ext


# Liquid Variable Fallbacks 
# (very useful!)
#
defaults:
    # ----------------------------------------------------
    - scope:
          path: ''
          type: 'lenses'
      values:
          layout: 'lens'
          emoji: 👻
    # ----------------------------------------------------
    - scope:
          path: ''
          type: 'category_pages'
      values:
          layout: 'category'
    # ----------------------------------------------------
    - scope:
          path: ''
      values:
          # Default Values (very important!)
          layout: 'default'
          favicon: icon-32-goat.png
          title: Kevin's Website
          description: Leader of the Internet Retro Revival Wave
          show_navigation: true
          hide_navigation: false
          twitter:
              card: summary
              title: Kevin's Website
              image: https://kevando.github.io/assets/images/aolfav.png
              description: Thanks for stopping by
          og:
              type: website
              title: Kevin's Fresh Website
              image:
              description: Thanks for chillin w me
    # ----------------------------------------------------
