


# Website Information
title: Kevando
description: Web Surfer


# Website Configuration
url: 'https://kevando.github.io'
google_analytics: UA-16078011-4


# Build Settings
theme: minima
plugins:
    - jekyll-feed

defaults:
    - scope:
          path: ''
      values:
          # Default Page Values
          layout: 'default'
          favicon: icon-32-goat.png
          meta_description: 'A website about me, Kevin Habich.'

# Content

collections:
    category:
        output: true
        defaults:
            - scope:
                  path: ''
                  type: category
              values:
                  layout: 'category'

sass:
    sass_dir: _sass
    style: compressed

# permalink: /:category/:year-:month-:day/:title
include: ['_pages']
