# ----------------------
# Basic Shit
# ----------------------

title: Kevando Online
description: Surfing the web revival wave
url: "https://kevando.github.io"
google_analytics: UA-16078011-4

# ----------------------
# Build Settings
# ----------------------

theme: minima
plugins:
  - jekyll-feed

# ----------------------
# Content Stuff
# ----------------------

defaults:
  - scope:
      path: ""
    values:
      layout: "base"

# ----------------------
# SASS/CSS 
# ----------------------

sass:
  sass_dir: _sass 
  style: compressed


# ----------------------
# Collections
# ----------------------

collections_dir: _collections