
# ----------------------
#    Site settings
# ----------------------

# title: Kevando
description: A repository of highlights.
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kevando.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Fresh
me:
  linkedin: "https://www.linkedin.com/in/kevando?utm_source=kevando"
  instagram: "https://www.instagram.com/kevando?utm_source=kevando"
  twitter: "https://www.twitter.com/kevando_?utm_source=kevando"
  vimeo: "https://www.vimeo.com/kevando?utm_source=kevando"
  soundcloud: "https://www.soundcloud.com/kevando?utm_source=kevando"
  disqus: "https://disqus.com/by/kevando"
  vine: "asdf"
  github: "sadf"

# Meta tag settings
twitter:
  username: kevando
  card: summary

# Tag Pages
tag_pages:
  - videos
  - soundcloud

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed


# ----------------------
#      SEO Shit
# ----------------------

google_analytics: UA-16078011-4


# ----------------------
#    Groups of Shit
# ----------------------

collections:
  category:
    output: true
  favs:
    output: true
    permalink: /<3/:name



defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"
