
# ------------------------
#      Website Info
# ------------------------

title: Kevin!
description: this my website
url: 'https://kevando.github.io'
google_analytics: UA-16078011-4


# ------------------------
#     Build Settings
# ------------------------

theme: minima
plugins:
    - jekyll-feed
sass:
    sass_dir: _sass\
    style: compressed
include: ['_pages']



# ------------------------
#       Collections
# ------------------------

collections:
    blog:
        output: true
        permalink: /:name:output_ext # Example: /photos
    posts:
        output: true
        permalink: /blog/:slug:output_ext # Example: /vr/2

# ------------------------
#     Default Values
# ------------------------

defaults:
    - scope:
          path: ''
      values:

        
          layout: default
          footer_class: 

          title: Kevando Online!
          description: 
          favicon: icon-32-goat.png

          # TWITTER
          twitter_card: summary
          twitter_image: assets/images/aolfav.png

          # FACEBOOK
          og_type: summary
          og_image: 
