# ---------------------------------
#   Basic Shit
# ---------------------------------

title: Kevando Online
description: Surfing the web revival wave
url: "https://kevando.github.io"
google_analytics: UA-16078011-4

# ---------------------------------
#   Build Settings
# ---------------------------------

theme: minima
plugins:
  - jekyll-feed

# ---------------------------------
#   Front Matter Defaults
# ---------------------------------

defaults:
  - scope:
      path: ""
    values:
      layout: "base"
      favicon: icon-32-goat.png

# ---------------------------------
#   Content
# ---------------------------------

collections:
  categories:
    permalink: /:collection/:name
# ---------------------------------
#   SASS/CSS 
# ---------------------------------

sass:
  sass_dir: _sass 
  style: compressed


# ---------------------------------
#   Content
# ---------------------------------

permalink: /:categories/:year/:month/:day/:title
include: ["_pages"]

