title:
description: Surfing the 90s design revival wave.
url: "https://kevando.github.io"
google_analytics: UA-16078011-4

twitter:
  username: kevando
  card: summary

# Tag Pages (not active)
tag_pages:
  - videos
  - soundcloud

# Build settings
theme: minima
plugins:
  - jekyll-feed



defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      meta:
        title: Default Meta Title
        description: Default Meta Description


sass:
  sass_dir: _sass # All .scss partials go here
  # style: compressed
